<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NotPersist_Value</name>
   <tag></tag>
   <elementGuidId>c802a057-2ccc-4a41-8d18-0f3c83832896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@controlholdername='NotPersist_']/div/div/div/ul/li/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@controlholdername='NotPersist_']/div/div/div/ul/li/span[1]</value>
   </webElementProperties>
</WebElementEntity>
