<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Persist_Value</name>
   <tag></tag>
   <elementGuidId>8bca5c87-8bd3-47e9-813e-11b197658199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@controlholdername='Persist_']/div/div/div/ul/li/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@controlholdername='Persist_']/div/div/div/ul/li/span[1]</value>
   </webElementProperties>
</WebElementEntity>
