<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LongInternal_Value</name>
   <tag></tag>
   <elementGuidId>3701b34b-1da8-4bed-bd70-e950cbf434b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='ListBox17ListBox17ListBox17ListBox17ListBox17ListBox17ListBox17ListBox17']/option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='ListBox17ListBox17ListBox17ListBox17ListBox17ListBox17ListBox17ListBox17']/option[2]</value>
   </webElementProperties>
</WebElementEntity>
