<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FormData_VariableLabel</name>
   <tag></tag>
   <elementGuidId>2e3c6d92-a179-4d2e-9b35-233fb04e5c53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@controlholdername='MultiSelectListBox8']/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@controlholdername='MultiSelectListBox8']/div/label/span</value>
   </webElementProperties>
</WebElementEntity>
