<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HBLabel</name>
   <tag></tag>
   <elementGuidId>d1c8343a-9f30-49fa-b6e2-ad7d7b038d74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@controlholdername='MultiSelectListBox6']/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@controlholdername='MultiSelectListBox6']/div/label/span</value>
   </webElementProperties>
</WebElementEntity>
