<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SystemData_VariableLabel</name>
   <tag></tag>
   <elementGuidId>b9e43d10-080a-4511-9dd6-7be3b4128eb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@controlholdername='MultiSelectListBox11']/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@controlholdername='MultiSelectListBox11']/div/label/span</value>
   </webElementProperties>
</WebElementEntity>
