<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClickApply_Filter</name>
   <tag></tag>
   <elementGuidId>47764fb0-f48c-4ee7-9ba1-1908bc57579c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='GridFilterPopupButtonOk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='GridFilterPopupButtonOk']</value>
   </webElementProperties>
</WebElementEntity>
