<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PL_Custom_Value</name>
   <tag></tag>
   <elementGuidId>3309f1ea-6c9b-45da-b4e7-8ad94d4ee0c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(.,'TestDisplayTwo')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(.,'TestDisplayTwo')]</value>
   </webElementProperties>
</WebElementEntity>
