<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NotContainOption_Option1</name>
   <tag></tag>
   <elementGuidId>d9d4ef81-275a-4120-bfbd-1f45ab6a64ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='NotContainOption']/Option[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='NotContainOption']/Option[1]</value>
   </webElementProperties>
</WebElementEntity>
