<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NotContain_Click</name>
   <tag></tag>
   <elementGuidId>b44c3ad3-4d58-41d9-b8da-ca65af190862</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@controlholdername='NotContain_']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@controlholdername='NotContain_']/div/div</value>
   </webElementProperties>
</WebElementEntity>
