<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NotContainOption_Option2</name>
   <tag></tag>
   <elementGuidId>e91676b2-de2e-4c22-9f8a-5c4f3c79861d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='NotContainOption']/Option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='NotContainOption']/Option[2]</value>
   </webElementProperties>
</WebElementEntity>
