<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FormDataHelp_Value</name>
   <tag></tag>
   <elementGuidId>824f5f13-9fb2-471c-a625-65e0de33588f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='HoverOnLabel_FormData']/option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='HoverOnLabel_FormData']/option[2]</value>
   </webElementProperties>
</WebElementEntity>
