<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M_Global_Value</name>
   <tag></tag>
   <elementGuidId>d75af304-605c-42f4-a217-53f7380724df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@controlholdername='M_Global']/div/div/div/ul/li/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@controlholdername='M_Global']/div/div/div/ul/li/span[1]</value>
   </webElementProperties>
</WebElementEntity>
