<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M_SC_Value</name>
   <tag></tag>
   <elementGuidId>c58095ad-6fd0-4491-9061-ab8179df097e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@controlholdername='M_SC']/div/div/div/ul/li/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@controlholdername='M_SC']/div/div/div/ul/li/span[1]</value>
   </webElementProperties>
</WebElementEntity>
