<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PL_Custom_Click</name>
   <tag></tag>
   <elementGuidId>bd523608-2a31-4f6e-8733-f3e1acd2a7e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@controlholdername='PL_Custom']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@controlholdername='PL_Custom']/div/div</value>
   </webElementProperties>
</WebElementEntity>
